#' Base dataset for record linkage example
#'
#' A dataset containing 3,300 person records with German, Turkish, and Polish names,
#' including addresses across various German cities. Approximately 5% of records are
#' intentional duplicates with small variations to simulate real-world data quality issues.
#'
#' @format A tibble with 3,300 rows and 7 variables:
#' \describe{
#'   \item{id_base}{Character identifier for base records (B0001-B3150)}
#'   \item{Vorname}{First name, weighted by ethnic group prevalence}
#'   \item{Nachname}{Last name, weighted by ethnic group prevalence}
#'   \item{Strasse}{Street name, including German street types}
#'   \item{Hausnummer}{House number, some with letter suffixes}
#'   \item{Ort}{City or town name}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated using weighted sampling from common German, Turkish,
#'   and Polish names (93%, 4%, and 3% respectively) and realistic German geography.
"base_example"

#' Target dataset for record linkage example
#'
#' A dataset containing 3,000 person records designed to match with \code{base_example}.
#' Approximately 80% of records correspond to records in the base dataset but
#' with realistic errors and variations (typos, abbreviated names, title additions,
#' street name variations). The remaining 20% are new records with no match.
#'
#' @format A tibble with 3,000 rows and 7 variables:
#' \describe{
#'   \item{actual_link}{The actual base_id in the simulation process}
#'   \item{id_target}{Character identifier for target records (T0001-T3600)}
#'   \item{Vorname}{First name, may include titles, initials, or middle names}
#'   \item{Nachname}{Last name, may contain typos or token swaps}
#'   \item{Strasse}{Street name with possible abbreviations or typos}
#'   \item{Hausnummer}{House number with possible letter suffixes}
#'   \item{Ort}{City or town name, may contain typos}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated by distorting 80% of \code{base_example} records
#'   and adding 20% new unmatched records.
"target_example"

#' Multilingual Street-Type Normalization Dictionary
#'
#' A curated cross-linguistic dictionary of street-type forms used for robust
#' address standardization and record linkage. Each entry maps a *variant*—
#' including abbreviations, orthographic alternatives, morphological forms,
#' and transliterated spellings—to a *canonical* street-type label.
#'
#' Unlike simple suffix lists, this dictionary encodes language-specific
#' normalization rules. Each variant is marked as either:
#'
#' - **"exact"** — the variant should only match a token when it appears
#'   *exactly*, e.g. `"st."` → `"STREET"` (English), `"pl"` → `"PLAZA"` (Spanish)
#' - **"suffix"** — the variant may safely match a token *ending with* that
#'   sequence, e.g. `"gatan"` → `"GATA"` (Swedish), `"strasse"` → `"STRASSE"`
#'   (German)
#'
#' By separating exact vs. suffix behavior and tagging each entry with an ISO
#' language code, \pkg{joinery} can normalize addresses *without* incorrect
#' transformations (e.g. preventing `"LINCOLN"` → `"LANE"`, or `"VICTOR"` →
#' `"RUE"`). This structure enables high-precision multilingual address cleaning.
#'
#' ## Languages Covered
#'
#' The dictionary currently includes major street-type systems from:
#'
#' - **German** — Straße, Gasse, Weg, Platz, Allee, …
#' - **English** — Street, Road, Avenue, Boulevard, Lane, …
#' - **French** — Rue, Avenue, Boulevard, Impasse, Quai, Chemin, …
#' - **Spanish** — Calle, Avenida, Paseo, Plaza, Camino, …
#' - **Italian** — Via, Piazza, Corso, Viale, …
#' - **Portuguese** — Rua, Avenida, Praça, Alameda, Travessa, …
#' - **Polish** — Ulica, Aleja, Plac, Osiedle, …
#' - **Dutch** — Straat, Laan, Weg, Plein, …
#' - **Turkish** — Sokak, Cadde, Bulvar, Meydan, …
#' - **Swedish** — Gata, Gatan, Vägen, Torg, …
#' - **Danish/Norwegian** — Gade, Vej, Plads, …
#' - **Greek (transliterated)** — Odos, Leoforos, Plateia
#' - **Russian (transliterated)** — Ulitsa, Prospekt, Pereulok, …
#'
#' Additional languages and street-type systems can be incorporated as needed.
#'
#' ## Use in `normalize_street()`
#'
#' `street_types` is used by [normalize_street()] to:
#'
#' - standardize street-type tokens to a canonical form,
#' - optionally apply language-specific suffix rules (`lang = "de"`, `"sv"`, etc.),
#' - avoid over-normalization by matching only valid variants for the specified
#'   language,
#' - support multilingual cleaning workflows in data preprocessing and record
#'   linkage.
#'
#' ## Format
#'
#' A tibble with four columns:
#'
#' \describe{
#'   \item{canonical}{Character string. The standardized street-type label in
#'     uppercase ASCII (e.g. `"STRASSE"`, `"AVENUE"`, `"PLAC"`).}
#'
#'   \item{variant}{Character string. A lowercase spelling, abbreviation,
#'     transliteration, or inflected form seen in raw address data (e.g.
#'     `"str."`, `"straße"`, `"avda"`, `"gatan"`).}
#'
#'   \item{type}{Either `"exact"` or `"suffix"`, indicating whether the variant
#'     should match only whole tokens or may safely match as a word-final
#'     suffix.}
#'
#'   \item{lang}{ISO 639-1 language code (e.g. `"de"`, `"en"`, `"fr"`, `"sv"`),
#'     used to restrict normalization to the appropriate street-type system.}
#' }
#'
#' @source Manually curated based on postal conventions, open datasets, and
#'   commonly observed street-name variations across languages. The dictionary is
#'   periodically expanded as new variants are encountered in real-world data.
"street_types"
