#' Base dataset for record linkage example
#'
#' A dataset containing 3,300 person records with German, Turkish, and Polish names,
#' including addresses across various German cities. Approximately 5% of records are
#' intentional duplicates with small variations to simulate real-world data quality issues.
#'
#' @format A tibble with 3,300 rows and 7 variables:
#' \describe{
#'   \item{id_base}{Character identifier for base records (B0001-B3150)}
#'   \item{Vorname}{First name, weighted by ethnic group prevalence}
#'   \item{Nachname}{Last name, weighted by ethnic group prevalence}
#'   \item{Strasse}{Street name, including German street types}
#'   \item{Hausnummer}{House number, some with letter suffixes}
#'   \item{Ort}{City or town name}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated using weighted sampling from common German, Turkish,
#'   and Polish names (93%, 4%, and 3% respectively) and realistic German geography.
"base_example"

#' Target dataset for record linkage example
#'
#' A dataset containing 3,000 person records designed to match with \code{base_example}.
#' Approximately 80% of records correspond to records in the base dataset but
#' with realistic errors and variations (typos, abbreviated names, title additions,
#' street name variations). The remaining 20% are new records with no match.
#'
#' @format A tibble with 3,000 rows and 7 variables:
#' \describe{
#'   \item{actual_link}{The actual base_id in the simulation process}
#'   \item{id_target}{Character identifier for target records (T0001-T3600)}
#'   \item{Vorname}{First name, may include titles, initials, or middle names}
#'   \item{Nachname}{Last name, may contain typos or token swaps}
#'   \item{Strasse}{Street name with possible abbreviations or typos}
#'   \item{Hausnummer}{House number with possible letter suffixes}
#'   \item{Ort}{City or town name, may contain typos}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated by distorting 80% of \code{base_example} records
#'   and adding 20% new unmatched records.
"target_example"

#' Workshop guild register (base) for record linkage examples
#'
#' A synthetic register of UK joinery and carpentry workshops, styled like an
#' excerpt from a Guild of Master Craftsmen trade roll. It is the clean base
#' table for the linkage examples: distinctive workshop names paired with
#' boilerplate trade and legal-form terms, so the rarity-versus-boilerplate
#' behaviour of the matcher is visible. Pairs with \code{workshop_listings}, the
#' messier external directory. Block on \code{(postcode_area, trade)}.
#'
#' @format A tibble with 982 rows and 15 variables:
#' \describe{
#'   \item{reg_no}{Character registration number, the base id. Most are
#'     \code{"GMC-#####"}; planted duplicates, homonyms, and shared-venue rows
#'     carry \code{"GMC-D####"}, \code{"GMC-H####"}, and \code{"GMC-V####"}
#'     prefixes respectively.}
#'   \item{workshop}{Canonical business name (distinctive stem plus trade and legal-form boilerplate)}
#'   \item{proprietor}{Proprietor name}
#'   \item{trade}{One of eight woodworking trades; half the blocking key}
#'   \item{legal_form}{Ltd, LLP, Partnership, or Sole Trader}
#'   \item{postcode_area}{UK outward-code area (e.g. "LS"); half the blocking key}
#'   \item{town}{Town for the postcode area}
#'   \item{address}{Street address}
#'   \item{established}{Year the workshop was established}
#'   \item{employees}{Headcount, varying with legal form}
#'   \item{apprentices}{Number of apprentices}
#'   \item{guild_member}{Logical, whether a current guild member}
#'   \item{sic}{UK SIC 2007 industry code for the trade}
#'   \item{true_entity}{Evaluation only. Same-entity key: planted duplicate rows
#'     share it, homonym workshops get distinct keys.}
#'   \item{gen_tier}{Evaluation only. Which generation tier the row belongs to.
#'     Three rows are \code{hub_trap}: short-named shared venues ("Trinity
#'     Workshops", "The Forge", "Riverside Works") that are themselves guild
#'     registered. Their two-token names are a forward-containment subset of every
#'     "<workshop>, <venue>" listing, so they bait an exact containment strategy
#'     into merging unrelated workshops; the \code{min_containment_tokens} guard
#'     blocks them.}
#' }
#' @source Synthetically generated. Distinct workshop identities come from a
#'   frozen LLM seed (\code{data-raw/llm_workshop_seed.R}); all geography,
#'   colour columns, planted duplicates, and homonyms are added by the seeded,
#'   offline \code{data-raw/generate_workshop_example.R}. Ships no real business.
#' @seealso \code{\link{workshop_listings}}
"workshop_register"

#' Workshop external directory (target) for record linkage examples
#'
#' A messier external directory of the same UK workshops as
#' \code{workshop_register}, the target table for cross-source linkage. Listings
#' carry the realistic distortions a scrappy directory introduces, planted as
#' labelled tiers (via \code{gen_tier}) so each exercises a specific joinery
#' feature: slogan-stuffed supersets (exact containment), movers that changed
#' postcode area (token blocking with global rarity), phonetic name variants
#' (Cologne/Soundex encoders), shared-venue and bare-category rows that bait
#' over-linking (the containment guards), and common-surname homonyms (ambiguity
#' and calibration). The matchable columns share names with
#' \code{workshop_register} so one formula serves both tables.
#'
#' @format A tibble with 844 rows and 8 variables:
#' \describe{
#'   \item{listing_id}{Character identifier for listings (e.g. "L00042")}
#'   \item{workshop}{Directory rendering of the business name, often messy}
#'   \item{proprietor}{Directory rendering of the proprietor name; may be missing}
#'   \item{trade}{Trade; half the blocking key}
#'   \item{postcode_area}{UK outward-code area; half the blocking key}
#'   \item{town}{Town for the postcode area}
#'   \item{actual_link}{Evaluation only. The \code{reg_no} this listing refers
#'     to, or \code{NA} for a workshop absent from the register.}
#'   \item{gen_tier}{Evaluation only. The feature-exercise tier (clean, slogan,
#'     variant, mover, phonetic, hub_member, hub_trap, category_trap,
#'     homonym_area, homonym_block, homonym_total, new).}
#' }
#' @source Synthetically generated by \code{data-raw/generate_workshop_example.R}
#'   from \code{workshop_register} and a frozen LLM seed of messy renderings.
#' @seealso \code{\link{workshop_register}}
"workshop_listings"

#' Multilingual Street-Type Normalization Dictionary
#'
#' A curated cross-linguistic dictionary of street-type forms used for robust
#' address standardization and record linkage. Each entry maps a *variant* -
#' including abbreviations, orthographic alternatives, morphological forms,
#' and transliterated spellings - to a *canonical* street-type label.
#'
#' Unlike simple suffix lists, this dictionary encodes language-specific
#' normalization rules. Each variant is marked as either:
#'
#' - **"exact"** - the variant should only match a token when it appears
#'   *exactly*, e.g. `"st."` → `"STREET"` (English), `"pl"` → `"PLAZA"` (Spanish)
#' - **"suffix"** - the variant may safely match a token *ending with* that
#'   sequence, e.g. `"gatan"` → `"GATA"` (Swedish), `"strasse"` → `"STRASSE"`
#'   (German)
#'
#' By separating exact vs. suffix behavior and tagging each entry with an ISO
#' language code, \pkg{joinery} can normalize addresses *without* incorrect
#' transformations (e.g. preventing `"LINCOLN"` → `"LANE"`, or `"VICTOR"` →
#' `"RUE"`). This structure enables high-precision multilingual address cleaning.
#'
#' ## Languages Covered
#'
#' The dictionary currently includes major street-type systems from:
#'
#' - **German** - Straße, Gasse, Weg, Platz, Allee, …
#' - **English** - Street, Road, Avenue, Boulevard, Lane, …
#' - **French** - Rue, Avenue, Boulevard, Impasse, Quai, Chemin, …
#' - **Spanish** - Calle, Avenida, Paseo, Plaza, Camino, …
#' - **Italian** - Via, Piazza, Corso, Viale, …
#' - **Portuguese** - Rua, Avenida, Praça, Alameda, Travessa, …
#' - **Polish** - Ulica, Aleja, Plac, Osiedle, …
#' - **Dutch** - Straat, Laan, Weg, Plein, …
#' - **Turkish** - Sokak, Cadde, Bulvar, Meydan, …
#' - **Swedish** - Gata, Gatan, Vägen, Torg, …
#' - **Danish/Norwegian** - Gade, Vej, Plads, …
#' - **Greek (transliterated)** - Odos, Leoforos, Plateia
#' - **Russian (transliterated)** - Ulitsa, Prospekt, Pereulok, …
#'
#' Additional languages and street-type systems can be incorporated as needed.
#'
#' ## Use in `normalize_street()`
#'
#' `street_types` is used by [normalize_street()] to:
#'
#' - standardize street-type tokens to a canonical form,
#' - optionally apply language-specific suffix rules (`lang = "de"`, `"sv"`, etc.),
#' - avoid over-normalization by matching only valid variants for the specified
#'   language,
#' - support multilingual cleaning workflows in data preprocessing and record
#'   linkage.
#'
#' ## Format
#'
#' A tibble with four columns:
#'
#' \describe{
#'   \item{canonical}{Character string. The standardized street-type label in
#'     uppercase ASCII (e.g. `"STRASSE"`, `"AVENUE"`, `"PLAC"`).}
#'
#'   \item{variant}{Character string. A lowercase spelling, abbreviation,
#'     transliteration, or inflected form seen in raw address data (e.g.
#'     `"str."`, `"straße"`, `"avda"`, `"gatan"`).}
#'
#'   \item{type}{Either `"exact"` or `"suffix"`, indicating whether the variant
#'     should match only whole tokens or may safely match as a word-final
#'     suffix.}
#'
#'   \item{lang}{ISO 639-1 language code (e.g. `"de"`, `"en"`, `"fr"`, `"sv"`),
#'     used to restrict normalization to the appropriate street-type system.}
#' }
#'
#' @source Manually curated based on postal conventions, open datasets, and
#'   commonly observed street-name variations across languages. The dictionary is
#'   periodically expanded as new variants are encountered in real-world data.
"street_types"

#' Multilingual Street-Name Stopwords
#'
#' Locative particles and articles that recur inside multi-word street names
#' but carry no discriminative signal for matching - German `AN DER`, French
#' `DE LA`, Italian `DELLA`, and so on. Used by [normalize_street()] when
#' `drop_stopwords = TRUE` to collapse e.g. `"An der Alster"` to `"ALSTER"`.
#'
#' The list is deliberately tight: only true prepositions and articles, never
#' adjectives (`"NEUE"`, `"GROSSE"`) or directionals that can themselves be the
#' distinguishing part of a name. Entries are uppercase ASCII so they join
#' directly against `normalize_street()`'s already-uppercased, transliterated
#' tokens. When a `lang` is supplied to `normalize_street()`, only that
#' language's particles are removed.
#'
#' ## Format
#'
#' A tibble with two columns:
#'
#' \describe{
#'   \item{stopword}{Character string. The particle in uppercase ASCII
#'     (e.g. `"AN"`, `"DER"`, `"DE"`, `"DELLA"`).}
#'   \item{lang}{ISO 639-1 language code (`"de"`, `"en"`, `"fr"`, `"es"`,
#'     `"it"`, `"pt"`, `"nl"`).}
#' }
#'
#' @seealso [normalize_street()], [street_types]
#'
#' @source Manually curated from common multi-word street-name patterns across
#'   languages. Expandable as new particles are encountered.
"street_stopwords"
