#' Base dataset for record linkage example
#'
#' A dataset containing 3,150 person records with German, Turkish, and Polish names,
#' including addresses across various German cities. Approximately 5% of records are
#' intentional duplicates with small variations to simulate real-world data quality issues.
#'
#' @format A tibble with 3,150 rows and 7 variables:
#' \describe{
#'   \item{id_base}{Character identifier for base records (B0001-B3150)}
#'   \item{Vorname}{First name, weighted by ethnic group prevalence}
#'   \item{Nachname}{Last name, weighted by ethnic group prevalence}
#'   \item{Strasse}{Street name, including German street types}
#'   \item{Hausnummer}{House number, some with letter suffixes}
#'   \item{Ort}{City or town name}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated using weighted sampling from common German, Turkish,
#'   and Polish names (93%, 4%, and 3% respectively) and realistic German geography.
"base_example"

#' Target dataset for record linkage example
#'
#' A dataset containing 3,000 person records designed to match with \code{base_example}.
#' Approximately 80% of records correspond to records in the base dataset but
#' with realistic errors and variations (typos, abbreviated names, title additions,
#' street name variations). The remaining 20% are new records with no match.
#'
#' @format A tibble with 3,000 rows and 7 variables:
#' \describe{
#'   \item{id_target}{Character identifier for target records (T0001-T3600)}
#'   \item{Vorname}{First name, may include titles, initials, or middle names}
#'   \item{Nachname}{Last name, may contain typos or token swaps}
#'   \item{Strasse}{Street name with possible abbreviations or typos}
#'   \item{Hausnummer}{House number with possible letter suffixes}
#'   \item{Ort}{City or town name, may contain typos}
#'   \item{Kreis}{Administrative district (Kreis)}
#' }
#' @source Synthetically generated by distorting 80% of \code{base_example} records
#'   and adding 20% new unmatched records.
"target_example"